name: Employee CI Pipeline
run-name: Employee CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
    build:
        name: Maven Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven
            - name: Build and Test & Package
              run: cd employee && mvn --batch-mode --update-snapshots verify
            - uses: actions/upload-artifact@v4
              with:
                name: Package
                path: employee/target/*.jar
    Sonar:
        name: SonarQube Analysis
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v6
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven
            - name: Cache SonarQube packages
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
               path: ~/.sonar/cache
               key: ${{ runner.os }}-sonar
               restore-keys: ${{ runner.os }}-sonar
            - name: Cache Maven packages
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                path: ~/.m2
                key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                restore-keys: ${{ runner.os }}-m2
            - name: Build and analyze
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: cd employee && mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pcoverage -Dsonar.projectKey=AnilGodavarthi26_EmployeeMicroservice
    Image_Build_and_Push_to_Registry:
        name: Employee Microservice Docker Image Build
        runs-on: ubuntu-latest
        needs: [build, Sonar]
        steps:
            - uses: actions/checkout@v6
            - name: Build Docker Image
              run: cd employee && docker build -t ${{vars.DOCKERHUB_USERNAME}}/employee:${{(github.build_number)}} .

            - name: Log in to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Push Image to DockerHub
              run: docker push ${{vars.DOCKERHUB_USERNAME}}/employee:${{ github.build_number }}

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                image-ref: '${{vars.DOCKERHUB_USERNAME}}/employee:${{ github.build_number }}'
                format: 'table'
                exit-code: '0'
                ignore-unfixed: true
                vuln-type: 'os,library'